site_name: Teselas vectoriales para hackató ATM
theme:
  name: 'material'
  language: 'es'
markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
repo_url: "https://github.com/geoinquiets/vt-hackato-atm"
pages:
- Home: index.md
- 1. Qué son: 1_teoria.md
- 2. Cómo visualizarlas: 2_visor_simple.md
- 3. Cómo publicar datos en un formato geojson a teselas vectoriales (mapbox online): 3_publicar.md
- 4. Cómo simbolizarlas (mapbox studio): 4_estilos.md
- 5. Cómo consumirlas (mapbox gl js): 5_visor_completo.md
- 6. Donde está la documentacion y los ejemplos: 6_documentacion.md
